#!/bin/sh

###############
## Autostart ##
###############

# Set wmname to LG3D
wmname LG3D

# Start pipewire
/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
/usr/bin/pipewire-media-session &

# Set wallpaper with nitrogen
nitrogen --restore &

# Start emacs in daemon mode
emacs --daemon &

# Start notification manager
dunst &

# Start status bar
dwmblocks &

# Start compositor
picom &

# Start the volume icon
pasystray &

# Configure keyboard
setxkbmap -model pc105 -layout us,gr -option grp:rctrl_toggle -option ctrl:nocaps &
xset r rate 260 32 &

# Start polkit-gnome
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Start network applet
cmst -m &

# Repeatedly start dwm for live restart
while true; do
    # Log stderror to a file 
    dwm 2> ~/.cache/dwm.log
done

