#!/bin/sh


###############
## Autostart ##
###############

# Set wmname to LG3D
wmname LG3D

# Set wallpaper with nitrogen
nitrogen --restore &

# Start emacs in daemon mode
emacs --daemon &

# Start notification manager
dunst &

# Start status bar
slstatus &

# Start compositor
picom &

# Start the volume icon and backlight controls
pnmixer &
xfce4-power-manager &

# Start network applet
cmst -m &

# Configure keyboard
setxkbmap -model pc105 -layout us,gr -option grp:rctrl_toggle -option ctrl:nocaps &

# Repeatedly start dwm for live restart
while true; do
    # Log stderror to a file 
    dwm 2> ~/.cache/dwm.log
done

